apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: quarkus-demo-pipeline-run-init
  namespace: quarkus-demo
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    tekton.dev/pipeline: quarkus-demo-pipeline
    type: pipeline
spec:
  params:
    - name: source-repo
      value: 'https://github.com/slallemand/quarkus-demo.git'
    - name: source-branch
      value: main
    - name: output-image
      value: image-registry.openshift-image-registry.svc:5000/image-registry.openshift-image-registry.svc:5000/quarkus-demo/quarkus-demo
  pipelineRef:
    name: quarkus-demo-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
