apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: quarkus-demo-run-pipeline
  namespace: quarkus-demo
spec:
  params:
    - name: git-revision
      description: The git revision
      default: main
    - name: git-repo-url
      description: The repo url
    - name: output-image
      description: reference of the image that will get created
      default: image-registry.openshift-image-registry.svc:5000/image-registry.openshift-image-registry.svc:5000/quarkus-demo/quarkus-demo
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: quarkus-demo-pipeline-$(uid)
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-branch
            value: $(tt.params.git-revision)
          - name: output-image
            value: $(tt.params.output-image)
        pipelineRef:
          name: quarkus-demo-pipeline
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: source-folder
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
